import { createContext, type ReactNode, useContext, useEffect, useMemo, useState } from "react";

export type Language = "en" | "zh";

const STORAGE_KEY = "are-u-human.language";

const en = {
  language: "Language",
  english: "English",
  chinese: "中文",
  siteLinks: "Site links",
  conduct: "conduct",
  activity: "activity",
  terms: "terms",
  privacy: "privacy",
  moderate: "moderate",
  chooseAction: "What would you like to do?",
  chooseRole: "Choose a role",
  askHuman: "ask a human",
  askQuestion: "Ask a Question",
  playAi: "play as ai",
  pretendAi: "Pretend to Be AI",
  humansOnly: "humans only",
  communityRule: "be kind. no personal info, links, or meetups.",
  helpLabel: "How Are u Human? works",
  strongestModel: "The strongest LLM model, powered by humans.",
  writeSomething: "write something",
  drawSomething: "draw something",
  chooseResponse: "Choose response type",
  balance: "Authoritative balance: {credits}",
  credit: "{count} credit",
  credits: "{count} credits",
  yourQuestion: "Your question",
  sendQuestion: "Send question",
  askPlaceholder: "ask anything a human can answer…",
  drawPlaceholder: "describe what you want someone to draw…",
  earnPlaceholder: "answer someone to earn another credit…",
  pendingQuestion: "one question is already pending",
  sendingCredit: "sending uses one credit",
  youAsked: "you asked",
  youAskedDrawing: "you asked for a drawing",
  aiThinking: "an AI is thinking…",
  online: "{online} online ({human} human · {ai} ai)",
  humanTagline: "humans make mistakes because that's what makes us human",
  beforeEnter: "before you enter",
  everyoneWelcome: "everyone is welcome to use Are u Human?",
  agreeConductPrefix: "i agree to follow the",
  codeOfConduct: "code of conduct",
  agreePolicyPrefix: "i agree to the",
  and: "and",
  privacyPolicy: "privacy policy",
  captchaError: "The anti-abuse check could not load. Please disable blockers and try again.",
  enterAnonymous: "enter anonymously",
  noAccount: "no email, username, password, or profile required.",
  antiAbuse: "Anti-abuse check",
  howItWorks: "how it works",
  instructionTitle: "your ai slop bores me",
  instructionIntro: "In a world looming with the threat of AI stealing your job, save humanity by stealing AI's job.",
  ruleCost: "each text or drawing prompt costs 1 credit.",
  ruleEarn: "to earn credits, switch to the AI tab and answer someone else's prompt with text or a drawing.",
  ruleIdleCredit: "if your balance stays at 0 for 5 minutes, you receive 1 recovery credit.",
  ruleSkip: "skip prompts you can't answer.",
  ruleOne: "you can have one question waiting at a time.",
  ruleNice: "be nice. No hate speech, personal information, links, or meetups.",
  ruleReport: "report harmful questions or answers.",
  gotIt: "got it",
  rereadRules: "you can reread the rules from the top navigation.",
  conductEyebrow: "Code of conduct",
  conductTitle: "Keep the humans safe.",
  conductLead: "Ask for help, stories, opinions, or drawings — never personal data or real-world contact.",
  doNotPost: "Do not post",
  doNotPostBody:
    "Personal or contact details, links, meetups, harassment, threats, doxxing, self-harm encouragement, hate speech, sexual content involving minors, or illegal content.",
  useReports: "Use reports",
  useReportsBody: "Report an assigned question or saved answer that breaks these rules. Repeated misuse may restrict access.",
  termsEyebrow: "Terms of use",
  termsTitle: "Entertainment, not expert advice.",
  termsLead:
    "Every answer is written by a real person, not AI. Do not rely on Are u Human? for medical, legal, financial, safety, or other important decisions.",
  whoCanUse: "Who can use it",
  whoCanUseBody: "Are u Human? is open to everyone, anywhere. By using it, you agree to follow the code of conduct.",
  creditsAvailability: "Credits and availability",
  creditsAvailabilityBody:
    "Each question costs one credit and an accepted answer earns one credit. If your balance stays at zero for five minutes, you receive one recovery credit. Matching is not guaranteed, and the service may change or be unavailable while in public beta.",
  privacyEyebrow: "Privacy",
  privacyTitle: "Anonymous by design.",
  privacyLead: "No email, username, password, or public profile is required to use Are u Human?",
  retained: "What is retained",
  retainedBody:
    "Activity stays only in this browser until you delete it. Questions are readable on the server for up to one hour; undelivered answers up to seven days. Delivered content is removed after your browser saves it. Report evidence is retained for 30 days, then purged. Operational metadata and provider backups may remain longer.",
  choices: "Your choices",
  choicesBody: "You can delete local activity at any time. Do not enter personal information in a question, answer, or drawing.",
  backHome: "Back home",
  activityTitle: "Saved on this browser.",
  activityNotice:
    "History is saved only on this browser. Clearing browser data permanently removes it and cannot be recovered on another device.",
  noActivity: "No local activity yet.",
  youAnswered: "You answered",
  withDrawing: " with a drawing",
  drawingFor: "Drawing for {question}",
  delete: "Delete",
  clearHistory: "Clear all history",
  deleteHistoryConfirm: "Delete all local history? This cannot be undone.",
  deleteAll: "Delete all",
  cancel: "Cancel",
  becomeMachine: "become the machine",
  machineReady: "You have two minutes to answer a stranger before the reservation expires.",
  machineReadyShort: "Answer a stranger before the reservation expires.",
  earnCredit: "+1 credit per answer",
  idleCreditCountdown: "free credit in {time}",
  startPlaying: "start playing",
  viewActivity: "view activity",
  answerSavedWarning: "Credit earned, but this answer could not be saved to this browser.",
  submittedTitle: "Answer submitted successfully",
  success: "great success (+1 credit. you now have {count})",
  anotherOne: "another one",
  noThanks: "no thanks",
  answerQuestion: "Answer this question",
  fromHuman: "FROM A HUMAN (+1C)",
  askedFor: "asked for {kind}",
  drawing: "a drawing",
  text: "text",
  skipTitle: "skip prompts you can’t answer!",
  skipBody: "Skip quickly to receive another available prompt.",
  write: "write",
  draw: "draw",
  yourAnswer: "Your answer",
  answerPlaceholder: "type your answer here…",
  characters: "{count}/750 characters",
  submitting: "Submitting…",
  sendDrawing: "Send drawing",
  submit: "Submit",
  skip: "Skip",
  report: "Report",
  reason: "Reason",
  reporting: "Reporting…",
  reportRelease: "Report and release",
  timeLeft: "time left",
  timeRemaining: "Time remaining: {time}",
  waitingPrompt: "waiting for a prompt…",
  checkNow: "check now",
  leaveQueue: "leave queue",
  humanAnswered: "A human answered your question",
  humanResponded: "a human responded",
  humanRespondedDrawing: "a human responded with a drawing",
  drawingResponse: "Drawing response to {question}",
  like: "Like",
  dislike: "Dislike",
  reportPlaceholder: "Why are you reporting this answer?",
  sendReport: "send report",
  reportReceived: "Report received.",
  thanksFeedback: "Thanks for your feedback.",
  moderationEyebrow: "Protected moderation",
  openReports: "Open reports",
  moderationNotice: "Moderation evidence is limited to the reported content and reason.",
  noReports: "No open reports.",
  reportType: "{type} report",
  evidence: "Evidence: {value}",
  reasonValue: "Reason: {value}",
  dismiss: "Dismiss",
  removeRefund: "Remove & refund",
  removeRestrict: "Remove & restrict",
  answerReady: "Answer ready",
  saveAnswer: "Save this answer before we remove it from the server.",
  retrySave: "Retry saving answer",
  questionExpired: "Question expired",
  questionExpiredTitle: "Your unanswered question expired.",
  questionExpiredBody: "Your credit has been refunded and the temporary question content was removed.",
  continue: "Continue",
  answerUnavailable: "Answer unavailable",
  answerUnavailableTitle: "This answer is no longer available.",
  answerUnavailableBody: "It was not saved to this browser before the temporary server copy expired.",
  findingQuestion: "Finding a question that needs a human answer…",
  loading: "Loading Are u Human?…",
  connectionLost: "Connection lost. We’ll retry automatically; your server state is safe.",
  liveDisconnected: "Live updates disconnected. We’ll keep checking automatically.",
  somethingWrong: "Something went wrong. Please try again.",
  drawingEditor: "Drawing editor",
  drawingTools: "Drawing tools",
  color: "color",
  useColor: "Use {color}",
  brush: "brush",
  brushSize: "Brush size {size}",
  eraser: "eraser",
  undo: "undo",
  clear: "clear",
  drawingCanvas: "Drawing canvas",
  drawingHelp: "Draw with a mouse, pen, or finger. Undo removes one stroke at a time.",
} as const;

type TranslationKey = keyof typeof en;

const zh: Record<TranslationKey, string> = {
  language: "语言",
  english: "English",
  chinese: "中文",
  siteLinks: "网站导航",
  conduct: "行为准则",
  activity: "活动记录",
  terms: "使用条款",
  privacy: "隐私",
  moderate: "审核",
  chooseAction: "你想做什么？",
  chooseRole: "选择角色",
  askHuman: "向真人提问",
  askQuestion: "向真人提问",
  playAi: "扮演 AI",
  pretendAi: "扮演 AI",
  humansOnly: "仅限真人",
  communityRule: "友善交流，不要分享个人信息、链接或约见。",
  helpLabel: "了解 Are u Human? 如何运作",
  strongestModel: "由真人驱动的最强 LLM 模型。",
  writeSomething: "写点什么",
  drawSomething: "画点什么",
  chooseResponse: "选择回答类型",
  balance: "当前余额：{credits}",
  credit: "{count} 个积分",
  credits: "{count} 个积分",
  yourQuestion: "你的问题",
  sendQuestion: "发送问题",
  askPlaceholder: "问一个真人能够回答的问题…",
  drawPlaceholder: "描述你希望对方画什么…",
  earnPlaceholder: "回答别人的问题以赚取积分…",
  pendingQuestion: "已有一个问题正在等待",
  sendingCredit: "发送将消耗 1 个积分",
  youAsked: "你问了",
  youAskedDrawing: "你请对方画了",
  aiThinking: "AI 正在思考…",
  online: "{online} 人在线（{human} 位提问者 · {ai} 位回答者）",
  humanTagline: "真人会犯错，因为这正是人之所以为人",
  beforeEnter: "进入之前",
  everyoneWelcome: "欢迎所有人使用 Are u Human?",
  agreeConductPrefix: "我同意遵守",
  codeOfConduct: "行为准则",
  agreePolicyPrefix: "我同意",
  and: "和",
  privacyPolicy: "隐私政策",
  captchaError: "反滥用验证无法加载，请关闭拦截工具后重试。",
  enterAnonymous: "匿名进入",
  noAccount: "无需邮箱、用户名、密码或公开资料。",
  antiAbuse: "反滥用验证",
  howItWorks: "玩法说明",
  instructionTitle: "AI 的活由你来抢",
  instructionIntro: "当 AI 似乎要抢走你的工作时，先扮演 AI，替真人回答问题。",
  ruleCost: "每个文字或绘图问题消耗 1 个积分。",
  ruleEarn: "切换到 AI 模式，用文字或绘图回答别人的问题即可赚取积分。",
  ruleIdleCredit: "积分连续保持为 0 满 5 分钟后，系统会自动补充 1 个积分。",
  ruleSkip: "不会回答的问题可以跳过。",
  ruleOne: "同一时间只能等待一个问题。",
  ruleNice: "请友善交流，不得发布仇恨言论、个人信息、链接或约见内容。",
  ruleReport: "遇到有害问题或回答时请举报。",
  gotIt: "知道了",
  rereadRules: "之后可从顶部导航再次查看规则。",
  conductEyebrow: "行为准则",
  conductTitle: "保护这里的每一位真人。",
  conductLead: "可以寻求帮助、故事、观点或绘图，但不要索取个人资料或现实联系。",
  doNotPost: "禁止发布",
  doNotPostBody: "个人或联系方式、链接、约见、骚扰、威胁、人肉搜索、鼓励自残、仇恨言论、涉及未成年人的色情内容或违法内容。",
  useReports: "使用举报",
  useReportsBody: "举报违反规则的已分配问题或已保存回答。重复滥用可能导致访问受限。",
  termsEyebrow: "使用条款",
  termsTitle: "仅供娱乐，不是专业建议。",
  termsLead: "每个回答都由真人撰写，而非 AI。请勿依赖 Are u Human? 作出医疗、法律、财务、安全或其他重要决定。",
  whoCanUse: "谁可以使用",
  whoCanUseBody: "Are u Human? 面向所有人开放。使用本服务即表示你同意遵守行为准则。",
  creditsAvailability: "积分与可用性",
  creditsAvailabilityBody:
    "每次提问消耗 1 个积分，每个被接受的回答赚取 1 个积分。积分连续为 0 满 5 分钟后，系统会自动补充 1 个积分。不保证一定匹配成功，公开测试期间服务可能变更或暂时不可用。",
  privacyEyebrow: "隐私",
  privacyTitle: "匿名是默认设计。",
  privacyLead: "使用 Are u Human? 无需邮箱、用户名、密码或公开资料。",
  retained: "保留哪些数据",
  retainedBody:
    "活动记录仅保存在此浏览器中，直到你主动删除。问题在服务器最多保留 1 小时，未领取回答最多保留 7 天。浏览器保存已送达内容后，服务器副本会被删除。举报证据保留 30 天后清除；运行元数据和服务商备份可能保留更久。",
  choices: "你的选择",
  choicesBody: "你可以随时删除本地活动记录。请勿在问题、回答或绘图中输入个人信息。",
  backHome: "返回首页",
  activityTitle: "保存在此浏览器中。",
  activityNotice: "历史记录只保存在此浏览器。清除浏览器数据会永久删除，且无法在其他设备恢复。",
  noActivity: "暂无本地活动。",
  youAnswered: "你回答了",
  withDrawing: "（绘图）",
  drawingFor: "为“{question}”绘制的图片",
  delete: "删除",
  clearHistory: "清空所有记录",
  deleteHistoryConfirm: "删除全部本地历史？此操作无法撤销。",
  deleteAll: "全部删除",
  cancel: "取消",
  becomeMachine: "成为这台机器",
  machineReady: "你有两分钟时间回答陌生人的问题。",
  machineReadyShort: "在预约过期前回答一位陌生人。",
  earnCredit: "每次回答 +1 积分",
  idleCreditCountdown: "{time} 后补充积分",
  startPlaying: "开始回答",
  viewActivity: "查看活动",
  answerSavedWarning: "积分已获得，但回答无法保存到此浏览器。",
  submittedTitle: "回答提交成功",
  success: "提交成功（+1 积分，现在共有 {count}）",
  anotherOne: "再来一个",
  noThanks: "暂时不要",
  answerQuestion: "回答这个问题",
  fromHuman: "来自真人（+1 积分）",
  askedFor: "需要{kind}",
  drawing: "绘图",
  text: "文字",
  skipTitle: "不会答就跳过！",
  skipBody: "立即跳过即可接收另一个可用问题。",
  write: "文字",
  draw: "绘图",
  yourAnswer: "你的回答",
  answerPlaceholder: "在这里输入回答…",
  characters: "{count}/750 字符",
  submitting: "提交中…",
  sendDrawing: "发送绘图",
  submit: "提交",
  skip: "跳过",
  report: "举报",
  reason: "原因",
  reporting: "举报中…",
  reportRelease: "举报并释放问题",
  timeLeft: "剩余时间",
  timeRemaining: "剩余时间：{time}",
  waitingPrompt: "正在等待问题…",
  checkNow: "立即检查",
  leaveQueue: "离开队列",
  humanAnswered: "一位真人回答了你的问题",
  humanResponded: "一位真人回复了",
  humanRespondedDrawing: "一位真人用绘图回复了",
  drawingResponse: "对“{question}”的绘图回答",
  like: "喜欢",
  dislike: "不喜欢",
  reportPlaceholder: "为什么举报这个回答？",
  sendReport: "发送举报",
  reportReceived: "举报已收到。",
  thanksFeedback: "感谢你的反馈。",
  moderationEyebrow: "受保护的审核",
  openReports: "待处理举报",
  moderationNotice: "审核证据仅包含被举报内容和举报原因。",
  noReports: "暂无待处理举报。",
  reportType: "{type}举报",
  evidence: "证据：{value}",
  reasonValue: "原因：{value}",
  dismiss: "忽略",
  removeRefund: "删除并退款",
  removeRestrict: "删除并限制用户",
  answerReady: "回答已就绪",
  saveAnswer: "请在服务器删除回答前先保存到本地。",
  retrySave: "重试保存回答",
  questionExpired: "问题已过期",
  questionExpiredTitle: "你的未回答问题已过期。",
  questionExpiredBody: "积分已退还，临时问题内容已从服务器删除。",
  continue: "继续",
  answerUnavailable: "回答不可用",
  answerUnavailableTitle: "此回答已无法获取。",
  answerUnavailableBody: "服务器临时副本过期前，它没有成功保存到此浏览器。",
  findingQuestion: "正在寻找需要真人回答的问题…",
  loading: "正在加载 Are u Human?…",
  connectionLost: "连接中断，我们会自动重试；服务器状态是安全的。",
  liveDisconnected: "实时更新已断开，我们会继续自动检查。",
  somethingWrong: "发生错误，请重试。",
  drawingEditor: "绘图编辑器",
  drawingTools: "绘图工具",
  color: "颜色",
  useColor: "使用颜色 {color}",
  brush: "画笔",
  brushSize: "画笔大小 {size}",
  eraser: "橡皮擦",
  undo: "撤销",
  clear: "清空",
  drawingCanvas: "画布",
  drawingHelp: "可使用鼠标、触控笔或手指绘图。每次撤销会移除一笔。",
};

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey, values?: Record<string, string | number>) => string;
};

function translate(language: Language, key: TranslationKey, values: Record<string, string | number> = {}) {
  return (language === "zh" ? zh[key] : en[key]).replace(/\{(\w+)\}/g, (_match, name: string) => String(values[name] ?? ""));
}

const LanguageContext = createContext<LanguageContextValue>({
  language: "en",
  setLanguage: () => undefined,
  t: (key, values) => translate("en", key, values),
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => (localStorage.getItem(STORAGE_KEY) === "zh" ? "zh" : "en"));

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language === "zh" ? "zh-CN" : "en";
  }, [language]);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage: setLanguageState,
      t: (key, values) => translate(language, key, values),
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export function LanguageSwitch() {
  const { language, setLanguage, t } = useLanguage();
  return (
    <div className="language-switch" role="group" aria-label={t("language")}>
      <button
        type="button"
        className={language === "en" ? "selected" : ""}
        aria-pressed={language === "en"}
        onClick={() => setLanguage("en")}
      >
        {t("english")}
      </button>
      <button
        type="button"
        className={language === "zh" ? "selected" : ""}
        aria-pressed={language === "zh"}
        onClick={() => setLanguage("zh")}
      >
        {t("chinese")}
      </button>
    </div>
  );
}
